version: '3.8'
services:
  db:
    container_name: db
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  server:
    container_name: server
    image: ping-server
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 3001:3001
    environment:
      NODE_ENV: development
      DB_HOST: db
      PORT: 3001
    links:
      - db
    volumes:
      - ./src:/usr/app/src
      - ./node_modules:/usr/app/node_modules
      - ./tsconfig.json:/usr/app/tsconfig.json
volumes:
  db:
    driver: local