version: '3.8'
services:
  postgres-test:
    container_name: postgres-test
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5433:5432'
    volumes: 
      - postgres-test:/var/lib/postgresql/data
  server-test:
    container_name: boilerplate-server-test
    image: boilerplate-server-test
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - postgres-test
    ports:
      - 3010:3001
    environment:
      NODE_ENV: test
      DB_HOST: postgres-test
      TEST_PORT: 3001 # 3010
      TEST_DB_PORT: 5432 # 5433
    links:
      - postgres-test
    volumes:
      - ./src:/usr/app/src
      - ./node_modules:/usr/app/node_modules
      - ./tsconfig.json:/usr/app/tsconfig.json
volumes:
  postgres-test:
    driver: local