version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes: 
      - postgres:/var/lib/postgresql/data
  server:
    container_name: server
    image: boilerplate-server
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - 3001:3001
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      PORT: 3001
    links:
      - postgres
    volumes:
      - ./src:/usr/app/src
      - ./node_modules:/usr/app/node_modules
      - ./tsconfig.json:/usr/app/tsconfig.json
volumes:
  postgres:
    driver: local