version: '3.8'
services:
  db-test:
    container_name: db-test
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5433:5432'
    volumes: 
      - ./db-test:/var/lib/postgresql/data
  server-test:
    container_name: server-test
    image: ping-server-test
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db-test
    ports:
      - 3010:3001
    environment:
      NODE_ENV: test
      DB_HOST: db-test
      PORT: 3001
    links:
      - db-test
    volumes:
      - ./src:/usr/app/src
      - ./node_modules:/usr/app/node_modules
      - ./tsconfig.json:/usr/app/tsconfig.json
volumes:
  db:
    driver: local