### GET server
GET http://localhost:3001/ping

### GET pings
GET http://localhost:3001/api/pings

### POST ping
POST http://localhost:3001/api/pings
Content-Type: application/json

{
    "pingType": "ping"
}