name: Pipeline

on:
  push:
    branches:
      - main
      - '**'
    pull_request:
      branches: [main]
      types: [opened, synchronize]

env:
  PORT: ${{ secrets.PORT }}
  DB_PORT: ${{ secrets.DB_PORT }}
  DB_HOST: ${{ secrets.DB_HOST }}
  TEST_PORT: ${{ secrets.TEST_PORT }}
  TEST_DB_PORT: ${{ secrets.TEST_DB_PORT }}

jobs:
  pipeline:
    runs-on: ubuntu-latest
    container: node:latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:

      - name: Install PostgreSQL client
        run: |
          apt-get update
          apt-get install --yes postgresql-client
  
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install && cd client && npm install

      # - name: Lint
      #   run: npm run lint

      # - name: Run server unit tests
      #   run: npm run test
      #   env:
      #     NODE_ENV: test
      #     DB_HOST: postgres
      #     TEST_PORT: 3001
      #     TEST_DB_PORT: 5432

      # - name: Run client unit tests
      #   run: npm run test:client

      - name: e2e tests
        uses: cypress-io/github-action@v4
        with:
          command: cd client && npm run test:e2e
          build: cd client && npm run build
          start: npm run server
          wait-on: http://localhost:3001
          # env:
          #   CYPRESS_BASE_URL: 'http://localhost:3001'