name: Pipeline

on:
  push:
  pull_request:
    branches: [main]

env:
  NODE_ENV: test
  DB_HOST: postgres
  TEST_PORT: 3001
  TEST_DB_PORT: 5432

jobs:
  pipeline:
    runs-on: ubuntu-latest
    container: node:latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
  
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install && cd client && npm install

      - name: Lint
        run: npm run lint

      - name: Run server unit tests
        run: npm run test

      - name: Run client unit tests
        run: cd client && npm run test
