name: Pipeline

on:
  push:
  pull_request:
    branches: [main]

jobs:

  unit-tests:
    runs-on: ubuntu-latest
    container: node:latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      NODE_ENV: test
      DB_HOST: postgres
      TEST_PORT: 3001
      TEST_DB_PORT: 5432
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install && cd client && npm install
      - name: Lint
        run: npm run lint
      - name: Run server unit tests
        run: npm run test
      - name: Run client unit tests
        run: cd client && npm run test

  e2e-tests:
    runs-on: ubuntu-latest
    container: cypress/browsers:node18.12.0-chrome107
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install && cd client && npm install
      - name: Setup and run e2e tests
        uses: cypress-io/github-action@v5
        with:
          working-directory: client
          install: false
          command: npm run test:e2e
          build: npm run build
          start: npm run server
          wait-on: http://localhost:3001
          browser: chrome
        env:
          NODE_ENV: production
          DB_HOST: postgres
          TEST_PORT: 3001
          TEST_DB_PORT: 5432
          CYPRESS_BASE_URL: http://localhost:3001

  tag:
    needs: [unit-tests, e2e-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Bump version on merge to main
        if: ${{ github.base_ref == 'main' && github.event.pull_request.merged == true }}
        uses: anothrNick/github-tag-action@1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: main