name: Pipeline

on:
  push:
  pull_request:
    branches: [main]

jobs:

  unit-tests:
    runs-on: ubuntu-latest
    container: node:latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      NODE_ENV: test
      DB_HOST: postgres
      TEST_PORT: 3001
      TEST_DB_PORT: 5432
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install && cd client && npm install
      - name: Lint
        run: npm run lint
      - name: Run server unit tests
        run: npm run test
      - name: Run client unit tests
        run: cd client && npm run test

  e2e-tests:
    runs-on: ubuntu-latest
    container: cypress/browsers:node18.12.0-chrome107
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install && cd client && npm install
      - name: Setup and run e2e tests
        uses: cypress-io/github-action@v5
        with:
          working-directory: client
          install: false
          command: npm run test:e2e
          build: npm run build
          start: npm run server
          wait-on: http://localhost:3001
          browser: chrome
        env:
          NODE_ENV: production
          DB_HOST: postgres
          TEST_PORT: 3001
          TEST_DB_PORT: 5432
          CYPRESS_BASE_URL: http://localhost:3001
      # https://github.com/bahmutov/eleventy-example/blob/main/.github/workflows/ci.yml#L27
      - name: e2e tests success
        if: ${{ success() }}
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "context": "e2e-tests",
            "state": "success",
            "description": "e2e tests passed",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'
      - name: e2e tests failure
        if: ${{ failure() }}
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "context": "e2e-tests",
            "state": "failure",
            "description": "e2e tests failed",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'
